fix(ff-a): default print verbosity
Changed to verbose print:
INFO:   Memory region 0x71fc000 - 0x7200000 allocated

SMMU id unspecified for a given peripheral:
WARNING: SMMUv3: Unexpected smmu-id:4294967295 specified in manifest

'FF-A RXTX Unmap API consecutive' test:
ERROR: No buffer pair registered on behalf of the caller.

Change-Id: Ibc20d7e7e0ab51f4343fbdf0914cf4aa2b8e71d4
Signed-off-by: Olivier Deprez <olivier.deprez@arm.com>